### PR TITLE
Decouple stats collector from usage reporter.

### LINKED ISSUE #1348: Spammy stats channel blocked warnings
```
10326 2017-02-16 20:59:04.664 [WARNING][32] stats_collector.go 154: Failed to report stats error=Stats channel blocked
```
Under heavy churn, we see the above warning in the logs, which seems to indicate that the usage reporting goroutine can't keep up.  That's fine, we'll just drop the update but it'd be good to understand it a bit better and make sure we're not losing all updates.

### PR DESCRIPTION
**Pull request by fasaxc**
Fixes #1348.

### CODE REVIEW

File: felix.go [hunk 1]
```diff
@@ -269,24 +268,46 @@ configRetry:
 	asyncCalcGraph := calc.NewAsyncCalcGraph(configParams, dpConnector.ToDataplane)
 
 	if configParams.UsageReportingEnabled {
-		// Usage reporting enabled, add stats collector to graph and
-		// start the usage reporting thread.
-		statsChan := make(chan calc.StatsUpdate, 1)
+		// Usage reporting enabled, add stats collector to graph.  When it detects an update
+		// to the stats, it makes a callback, which we use to send an update on a channel.
+		// We use a buffered channel here to avoid blocking the calculation graph.
+		statsChanIn := make(chan calc.StatsUpdate, 1)
```
Comment (neiljerram) [inline felix.go]: Is there really still a reason for this 1-size buffer?

Comment (fasaxc) [inline felix.go]: My thinking was that it means that the calc graph won't have to wait for the buffer goroutine to complete its loop (so we get a pipelining effect).  Could well believe it makes no real difference in practice though!

Comment (neiljerram) [inline felix.go]: Fair enough.  Happy to check my understanding, but also happy to approve the change as is.
