### PR TITLE
Change the main IP set prefix.

### LINKED ISSUE #1694: Upgrading from 3.0.x to master (with network sets) causes ipset swap failures
```
2018-02-07 13:38:19.720 [WARNING][1385] ipsets.go 619: Failed to complete ipset restore, IP sets may be out-of-sync. closeErr=<nil> commitErr=<nil> family="inet" flushErr=<nil> input="create cali4tmasq-ipam-pools hash:net family inet maxelem 1048576\nadd cali4tmasq-ipam-pools 192.168.0.0/16\nswap cali4-masq-ipam-pools cali4tmasq-ipam-pools\ndestroy cali4tmasq-ipam-pools\ncreate cali4tthis-host hash:ip family inet maxelem 1048576\nadd cali4tthis-host 172.17.0.1\nadd cali4tthis-host 192.168.71.64\nadd cali4tthis-host 127.0.0.1\nadd cali4tthis-host 10.128.0.11\nswap cali4-this-host cali4tthis-host\ndestroy cali4tthis-host\ndestroy cali4ts:WZzrxARe9iGAPn7feWsQ4Hi\ncreate cali4ts:WZzrxARe9iGAPn7feWsQ4Hi hash:net family inet maxelem 1048576\nadd cali4ts:WZzrxARe9iGAPn7feWsQ4Hi 192.168.71.85/32\nswap cali4-s:WZzrxARe9iGAPn7feWsQ4Hi cali4ts:WZzrxARe9iGAPn7feWsQ4Hi\ndestroy cali4ts:WZzrxARe9iGAPn7feWsQ4Hi\ncreate cali4tall-hosts hash:ip family inet maxelem 1048576\nadd cali4tall-hosts 10.128.0.13\nadd cali4tall-hosts 10.128.0.12\nadd cali4tall-hosts 10.128.0.10\nadd cali4tall-hosts 10.128.0.11\nswap cali4-all-hosts cali4tall-hosts\ndestroy cali4tall-hosts\ncreate cali4tall-ipam-pools hash:net family inet maxelem 1048576\nadd cali4tall-ipam-pools 192.168.0.0/16\nswap cali4-all-ipam-pools cali4tall-ipam-pools\ndestroy cali4tall-ipam-pools\nCOMMIT\n" processErr=exit status 1 stderr="ipset v6.34: Error in line 15: The sets cannot be swapped: their type does not match\n" stdout="" writeErr=<nil>

```

## Expected Behavior

No error.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Felix version (if using Felix binary directly `calico-felix --version`):
* And/Or, `calico/node` container version (if running Felix in a container):
* Which orchestrator are you using (e.g. Kubernetes, OpenStack, Docker, Mesos):
* Orchestrator version (if used):
* Etcd version (if using etcd datastore driver):
* Operating System and version:
* Link to your project (optional):

### PR DESCRIPTION
**Pull request by fasaxc**
## Description

Change the IP set prefix to work around the fact that the kernel can't do an `ipset swap` between two IP sets of different type.  The main IP set type used by felix was changed as part of the network sets PR, resulting in failures after upgrade from previous versions.

Fixes #1694.

## Todos
- [x] Unit tests (full coverage)
- [ ] Integration tests (delete as appropriate) In plan/Not needed/Done
- [ ] Documentation
- [ ] Backport
- [ ] Release note

## Release Note

```release-note
None required
```

### CODE REVIEW

File: ipsets/ipset_defs.go [hunk 1]
```diff
@@ -244,6 +244,21 @@ type IPVersionConfig struct {
 	ourNamePrefixesRegexp *regexp.Regexp
 }
 
+const (
+	// mainIpsetToken is the character that we append to the versioned prefix "cali4" or "cali6" to
+	// get the main IP set name prefix.   To minimise the length of the prefix (and hence preser
```
Comment (neiljerram) [inline ipsets/ipset_defs.go]: "preserve"?
