### PR TITLE
Fix ifacemonitor UT concurrent map access

### LINKED ISSUE #1296: "concurrent map read and map write" in ifacemonitor UT
Seen in jenkins test run: http://localhost:8080/job/unit-test/293/console
```
[1485594484] [1mIfacemonitor Suite[0m - 1/1 specs fatal error: concurrent map read and map write

goroutine 15 [running]:
runtime.throw(0x153b532, 0x21)
	/usr/local/go/src/runtime/panic.go:566 +0x95 fp=0xc4204c7670 sp=0xc4204c7650
runtime.mapaccess2_faststr(0x139b3a0, 0xc420396e40, 0x151ae65, 0x4, 0x68d26ec5, 0xc420397530)
	/usr/local/go/src/runtime/hashmap_fast.go:306 +0x52b fp=0xc4204c76d0 sp=0xc4204c7670
github.com/projectcalico/felix/ifacemonitor_test.(*netlinkTest).AddrList(0xc420396c30, 0x1d62980, 0xc42006c480, 0x2, 0xc420397530, 0xc4203bd220, 0x151bbb0, 0x14, 0xc)
	/go/src/github.com/projectcalico/felix/ifacemonitor/ifacemonitor_test.go:187 +0x73 fp=0xc4204c7750 sp=0xc4204c76d0
github.com/projectcalico/felix/ifacemonitor.(*InterfaceMonitor).storeAndNotifyLink(0xc4200157c0, 0x131fd01, 0x1d62980, 0xc42006c480)
	github.com/projectcalico/felix/ifacemonitor/_obj/iface_monitor.go:260 +0x6d7 fp=0xc4204c7a20 sp=0xc4204c7750
github.com/projectcalico/felix/ifacemonitor.(*InterfaceMonitor).resync(0xc4200157c0, 0x1, 0x1)
	github.com/projectcalico/felix/ifacemonitor/_obj/iface_monitor.go:302 +0x269 fp=0xc4204c7b48 sp=0xc4204c7a20
github.com/projectcalico/felix/ifacemonitor.(*InterfaceMonitor).MonitorInterfaces(0xc4200157c0)
	github.com/projectcalico/felix/ifacemonitor/_obj/iface_monitor.go:124 +0xc08 fp=0xc4204c7f88 sp=0xc4204c7b48
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc4204c7f90 sp=0xc4204c7f88
created by github.com/projectcalico/felix/ifacemonitor_test.glob..func1.1
	/go/src/github.com/projectcalico/felix/ifacemonitor/ifacemonitor_test.go:296 +0x480

goroutine 1 [chan receive]:
testing.(*T).Run(0xc42006c0c0, 0x152913b, 0x10, 0x15d8d48, 0xc420661c38)
	/usr/local/go/src/testing/testing.go:647 +0x316
testing.RunTests.func1(0xc42006c0c0)
	/usr/local/go/src/testing/testing.go:793 +0x6d
testing.tRunner(0xc42006c0c0, 0xc420661d28)
	/usr/local/go/src/testing/testing.go:610 +0x81
testing.RunTests(0x15dead8, 0x1db87a0, 0x1, 0x1, 0xc420101a20)
	/usr/local/go/src/testing/testing.go:799 +0x2f5
testing.(*M).Run(0xc420661e88, 0x155a74c)
	/usr/local/go/src/testing/testing.go:743 +0x85
main.main()
	github.com/projectcalico/felix/ifacemonitor/_test/_testmain.go:328 +0x1c0

goroutine 5 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:116 +0x157
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 17 [chan receive]:
github.com/projectcalico/felix/vendor/github.com/golang/glog.(*loggingT).flushDaemon(0x1dc9220)
	/go/src/github.com/projectcalico/felix/vendor/github.com/golang/glog/glog.go:879 +0x7a
created by github.com/projectcalico/felix/vendor/github.com/golang/glog.init.1
	/go/src/github.com/projectcalico/felix/vendor/github.com/golang/glog/glog.go:410 +0x21d

goroutine 19 [select, locked to thread]:
runtime.gopark(0x15df268, 0x0, 0x151d6a8, 0x6, 0x18, 0x2)
	/usr/local/go/src/runtime/proc.go:259 +0x13a
runtime.selectgoImpl(0xc42001af30, 0x0, 0x18)
	/usr/local/go/src/runtime/select.go:423 +0x11d9
runtime.selectgo(0xc42001af30)
	/usr/local/go/src/runtime/select.go:238 +0x1c
runtime.ensureSigM.func1()
	/usr/local/go/src/runtime/signal1_unix.go:304 +0x2f3
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1

goroutine 13 [runnable]:
fmt.(*pp).doPrintf(0xc4204ba000, 0x1519ef9, 0x2, 0xc42013eee8, 0x1, 0x1)
	/usr/local/go/src/fmt/print.go:933
fmt.Fprintf(0x1d59d40, 0xc4204bc000, 0x1519ef9, 0x2, 0xc42013eee8, 0x1, 0x1, 0x10, 0x131fd00, 0x0)
	/usr/local/go/src/fmt/print.go:181 +0x76
github.com/projectcalico/felix/vendor/github.com/Sirupsen/logrus.(*TextFormatter).appendValue(0xc42000e0e0, 0xc4204bc000, 0x131fd00, 0xc420407550)
	/go/src/github.com/projectcalico/felix/vendor/github.com/Sirupsen/logrus/text_formatter.go:154 +0x398
github.com/projectcalico/felix/vendor/github.com/Sirupsen/logrus.(*TextFormatter).appendKeyValue(0xc42000e0e0, 0xc4204bc000, 0x151a5f4, 0x3, 0x131fd00, 0xc420407550)
	/go/src/github.com/projectcalico/felix/vendor/github.com/Sirupsen/logrus/text_formatter.go:144 +0x82
github.com/projectcalico/felix/vendor/github.com/Sirupsen/logrus.(*TextFormatter).Format(0xc42000e0e0, 0xc4204b8280, 0xc42000e100, 0x14e0020, 0xc4204bc000, 0xc420368240, 0xc4204480b0)
	/go/src/github.com/projectcalico/felix/vendor/github.com/Sirupsen/logrus/text_formatter.go:88 +0x5bc
github.com/projectcalico/felix/vendor/github.com/Sirupsen/logrus.Entry.log(0xc4200140f0, 0xc420368210, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x131fd04, ...)
	/go/src/github.com/projectcalico/felix/vendor/github.com/Sirupsen/logrus/entry.go:105 +0x2cd
github.com/projectcalico/felix/vendor/github.com/Sirupsen/logrus.(*Entry).Info(0xc4204b8230, 0xc42013f288, 0x1, 0x1)
	/go/src/github.com/projectcalico/felix/vendor/github.com/Sirupsen/logrus/entry.go:140 +0xaa
github.com/projectcalico/felix/ifacemonitor_test.(*netlinkTest).signalAddr(0xc420396c30, 0x151ae65, 0x4, 0x15259be, 0xe, 0x1d62901)
	/go/src/github.com/projectcalico/felix/ifacemonitor/ifacemonitor_test.go:152 +0x1f8
github.com/projectcalico/felix/ifacemonitor_test.(*netlinkTest).addAddr(0xc420396c30, 0x151ae65, 0x4, 0x15259be, 0xe)
	/go/src/github.com/projectcalico/felix/ifacemonitor/ifacemonitor_test.go:129 +0x20b
github.com/projectcalico/felix/ifacemonitor_test.glob..func1.2()
	/go/src/github.com/projectcalico/felix/ifacemonitor/ifacemonitor_test.go:311 +0x130
github.com/projectcalico/felix/vendor/github.com/onsi/ginkgo/internal/leafnodes.(*runner).runSync(0xc4200ddce0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/projectcalico/felix/vendor/github.com/onsi/ginkgo/internal/leafnodes/runner.go:109 +0x9c
github.com/projectcalico/felix/vendor/github.com/onsi/ginkgo/internal/leafnodes.(*runner).run(0xc4200ddce0, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/projectcalico/felix/vendor/github.com/onsi/ginkgo/internal/leafnodes/runner.go:63 +0xe1
github.com/projectcalico/felix/vendor/github.com/onsi/ginkgo/internal/leafnodes.(*ItNode).Run(0xc42048f2c0, 0x1d5ab00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/projectcalico/felix/vendor/github.com/onsi/ginkgo/internal/leafnodes/it_node.go:25 +0x64
github.com/projectcalico/felix/vendor/github.com/onsi/ginkgo/internal/spec.(*Spec).runSample(0xc420441860, 0x0, 0x1d5ab00, 0xc420011080)
	/go/src/github.com/projectcalico/felix/vendor/github.com/onsi/ginkgo/internal/spec/spec.go:176 +0x4fd
github.com/projectcalico/felix/vendor/github.com/onsi/ginkgo/internal/spec.(*Spec).Run(0xc420441860, 0x1d5ab00, 0xc420011080)
	/go/src/github.com/projectcalico/felix/vendor/github.com/onsi/ginkgo/internal/spec/spec.go:127 +0xd4
github.com/projectcalico/felix/vendor/github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpec(0xc420284fc0, 0xc420441860, 0xc4204b4ba0)
	/go/src/github.com/projectcalico/felix/vendor/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:172 +0xed
github.com/projectcalico/felix/vendor/github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpecs(0xc420284fc0, 0x15d9801)
	/go/src/github.com/projectcalico/felix/vendor/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:142 +0x2b3
github.com/projectcalico/felix/vendor/github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).Run(0xc420284fc0, 0x12)
	/go/src/github.com/projectcalico/felix/vendor/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:61 +0xf0
github.com/projectcalico/felix/vendor/github.com/onsi/ginkgo/internal/suite.(*Suite).Run(0xc420014690, 0x7fb97b7a4688, 0xc42006c180, 0x152c659, 0x12, 0xc42023de70, 0x1, 0x1, 0x1d6ef60, 0xc420011080, ...)
	/go/src/github.com/projectcalico/felix/vendor/github.com/onsi/ginkgo/internal/suite/suite.go:59 +0x23b
github.com/projectcalico/felix/vendor/github.com/onsi/ginkgo.RunSpecsWithCustomReporters(0x1d5f980, 0xc42006c180, 0x152c659, 0x12, 0xc42013ff10, 0x1, 0x1, 0x1)
	/go/src/github.com/projectcalico/felix/vendor/github.com/onsi/ginkgo/ginkgo_dsl.go:218 +0x27b
github.com/projectcalico/felix/vendor/github.com/onsi/ginkgo.RunSpecs(0x1d5f980, 0xc42006c180, 0x152c659, 0x12, 0xc404b0a956)
	/go/src/github.com/projectcalico/felix/vendor/github.com/onsi/ginkgo/ginkgo_dsl.go:199 +0x208
github.com/projectcalico/felix/ifacemonitor_test.TestIfacemonitor(0xc42006c180)
	/go/src/github.com/projectcalico/felix/ifacemonitor/ifacemonitor_suite_test.go:31 +0x64
testing.tRunner(0xc42006c180, 0x15d8d48)
	/usr/local/go/src/testing/testing.go:610 +0x81
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:646 +0x2ec

goroutine 14 [chan receive]:
github.com/projectcalico/felix/vendor/github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).registerForInterrupts(0xc420284fc0)
	/go/src/github.com/projectcalico/felix/vendor/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:194 +0x13f
created by github.com/projectcalico/felix/vendor/github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).Run
	/go/src/github.com/projectcalico/felix/vendor/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:56 +0x74
```

### PR DESCRIPTION
**Pull request by neiljerram**
Fixes #1296

### CODE REVIEW

File: ifacemonitor/ifacemonitor_test.go [hunk 1]
```diff
@@ -39,8 +40,9 @@ type netlinkTest struct {
 	addrUpdates    chan netlink.AddrUpdate
 	userSubscribed chan int
 
-	nextIndex int
-	links     map[string]linkModel
+	nextIndex  int
+	links      map[string]linkModel
+	linksMutex *sync.Mutex
```
Comment (fasaxc) [inline ifacemonitor/ifacemonitor_test.go]: I believe it's idiomatic to use `sync.Mutex` instead of `*sync.Mutex`, then you can take advantage of the fact that a `zero` mutex is ready for use.

File: ifacemonitor/ifacemonitor_test.go [hunk 2]
```diff
@@ -63,26 +66,31 @@ func (nl *netlinkTest) addLink(name string) {
 		state: "down",
 		addrs: set.New(),
 	}
+	nl.linksMutex.Unlock()
```
Comment (fasaxc) [inline ifacemonitor/ifacemonitor_test.go]: Should the mutex guard `nextIndex` too?  I'm not sure there's an issue but I'm having a hard time proving that to myself, whereas if it was guarded, it'd be easier.

File: ifacemonitor/ifacemonitor_test.go [hunk 3]
```diff
@@ -179,12 +196,15 @@ func (nl *netlinkTest) LinkList() ([]netlink.Link, error) {
...
 	return links, nil
 }
 
 func (nl *netlinkTest) AddrList(link netlink.Link, family int) ([]netlink.Addr, error) {
 	name := link.Attrs().Name
+	nl.linksMutex.Lock()
 	model, prs := nl.links[name]
+	nl.linksMutex.Unlock()
```
Comment (fasaxc) [inline ifacemonitor/ifacemonitor_test.go]: I think the loop below needs to be guarded by the mutex too.  `addAddr()` could be updating the set that you're iterating over here.

(To be clear, I'm not sure if that can actually happen in the scope of the test, but it's easier/more robust to fix than it is to reason about the large-scale behaviour of the test.)

**Comment by neiljerram** [comment]
@fasaxc All comments addressed, I believe.
