### PR TITLE
Work around temporary IP set deletion failure

### LINKED ISSUE #1745: Felix crashes on ipset programming failure
Seen in a calico ST run on semaphore (which has since expired).

```
2018-03-16 18:50:10 WARNING 509 2018-03-16 18:50:10.159 [WARNING][509] ipsets.go 619: Failed to complete ipset restore, IP sets may be out-of-sync. closeErr=<nil> commitErr=<nil> family="inet" flushErr=<nil> input="create cali4tmasq-ipam-pools hash:net family inet maxelem 1048576\nswap cali40masq-ipam-pools cali4tmasq-ipam-pools\ndestroy cali4tmasq-ipam-pools\ncreate cali4tthis-host hash:ip family inet maxelem 1048576\nadd cali4tthis-host 127.0.0.1\nadd cali4tthis-host 172.18.0.1\nadd cali4tthis-host 192.168.146.130\nadd cali4tthis-host 172.17.0.3\nswap cali40this-host cali4tthis-host\ndestroy cali4tthis-host\ndestroy cali4ts:mHDOqpY19uvpC-3qX-0xeq2\ncreate cali4ts:mHDOqpY19uvpC-3qX-0xeq2 hash:net family inet maxelem 1048576\nadd cali4ts:mHDOqpY19uvpC-3qX-0xeq2 192.168.146.128/32\nadd cali4ts:mHDOqpY19uvpC-3qX-0xeq2 192.168.142.64/32\nswap cali40s:mHDOqpY19uvpC-3qX-0xeq2 cali4ts:mHDOqpY19uvpC-3qX-0xeq2\ndestroy cali4ts:mHDOqpY19uvpC-3qX-0xeq2\ncreate cali4tall-hosts hash:ip family inet maxelem 1048576\nadd cali4tall-hosts 172.17.0.3\nadd cali4tall-hosts 172.17.0.2\nswap cali40all-hosts cali4tall-hosts\ndestroy cali4tall-hosts\ncreate cali4tall-ipam-pools hash:net family inet maxelem 1048576\nadd cali4tall-ipam-pools 192.168.128.0/17\nswap cali40all-ipam-pools cali4tall-ipam-pools\ndestroy cali4tall-ipam-pools\nCOMMIT\n" processErr=exit status 1 stderr="ipset v6.34: Error in line 11: Set cannot be destroyed: it is in use by a kernel component\n" stdout="" writeErr=<nil>

2018-03-16 18:50:10 WARNING 509 2018-03-16 18:50:10.160 [WARNING][509] ipsets.go 268: Failed to update IP sets. Marking dataplane for resync. error=exit status 1 family="inet"```
```

Found this flake in one of the Calico STs, causing a panic in Felix.

> Error in line 11: Set cannot be destroyed: it is in use by a kernel component"

We were hitting this code: https://github.com/projectcalico/felix/blob/master/ipsets/ipsets.go#L279-L282

From @fasaxc:

```
Ooh, that’s hit when an update fails, not a deletion

Ooh, but maybe we delete as part of a resync, which we trigger on a retry…

shaun [11:10 AM]
Nope, it’s just that we’re doing a delete of a temporary IP set as part of an update
Hmm, maybe we need to queue those up with the other deletions instead of assuming that they’re unreferenced immediately
```
## Expected Behavior

Should not crash.

## Current Behavior

It crashes.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Felix version (if using Felix binary directly `calico-felix --version`):
* And/Or, `calico/node` container version (if running Felix in a container):
* Which orchestrator are you using (e.g. Kubernetes, OpenStack, Docker, Mesos):
* Orchestrator version (if used):
* Etcd version (if using etcd datastore driver):
* Operating System and version:
* Link to your project (optional):

### PR DESCRIPTION
**Pull request by fasaxc**
## Description

- Use unique temporary IP set names.
- Wait for next resync to retry deletions to avoid tight loop.

Fixes #1745 

## Todos
- [x] Unit tests (full coverage)
- [ ] Integration tests (delete as appropriate) In plan/Not needed/Done
- [ ] Documentation
- [ ] Backport
- [ ] Release note

## Release Note

```release-note
Felix now uses unique temporary IP set names; this works around transient deletion failures and failures caused by other apps incorrectly referencing Calico IP sets.
```

### CODE REVIEW

File: ipsets/ipsets.go [hunk 1]
```diff
@@ -792,6 +820,27 @@ func (s *IPSets) ApplyDeletions() {
...
+		setName := item.(string)
+		logCxt := s.logCxt.WithField("setName", setName)
+		if s.existingIPSetNames.Contains(setName) {
+			logCxt.Info("Deleting IP set.")
+			if err := s.deleteIPSet(setName); err != nil {
+				// Log and carry on; we'll try again in ApplyDeletions().
+				logCxt.WithError(err).Warning("Failed to delete temporary IP set. Will retry...")
+			}
+		} else {
+			// Success! Remove from the main pending deletions set too.
```
Comment (neiljerram) [inline ipsets/ipsets.go]: This comment looks misplaced, or else the two possible `else` branches here are confused.  *This* `else` branch is for `// The IP set that we meant to delete has already disappeared (somehow).`, and it looks like we're completely missing the `else` branch for `// Successfully cleaned up temporary IP set.`

Comment (fasaxc) [reply ipsets/ipsets.go]: Yes, you're right, added the else to the wrong conditional, doh!

File: ipsets/ipsets.go [hunk 2]
```diff
@@ -792,6 +820,27 @@ func (s *IPSets) ApplyDeletions() {
...
+		logCxt := s.logCxt.WithField("setName", setName)
+		if s.existingIPSetNames.Contains(setName) {
+			logCxt.Info("Deleting IP set.")
+			if err := s.deleteIPSet(setName); err != nil {
+				// Log and carry on; we'll try again in ApplyDeletions().
+				logCxt.WithError(err).Warning("Failed to delete temporary IP set. Will retry...")
+			} else {
+				// Success! Remove from the main pending deletions set too.
+				logCxt.WithField("setName", setName).Info("Successfully removed left-over temporary IP set.")
+				s.pendingIPSetDeletions.Discard(item)
```
Comment (neiljerram) [inline ipsets/ipsets.go]: 1. Should this be `s.pendingTempIPSetDeletions.Discard(item)` ?

2. What is the difference between that and `return set.RemoveItem` ?  Would it be better to use just one of those options, both times?

File: ipsets/ipsets.go [hunk 3]
```diff
@@ -792,6 +820,27 @@ func (s *IPSets) ApplyDeletions() {
...
+			}
+		}
```
Comment (neiljerram) [inline ipsets/ipsets.go]: Should there be an else branch here too, that also removes from `s.pendingTempIPSetDeletions` (however that is done)?

Comment (fasaxc) [reply ipsets/ipsets.go]: No, that's handled by returning `set.RemoveItem`

Comment (neiljerram) [reply ipsets/ipsets.go]: Ah OK, I see now - sorry for the noise!

File: ipsets/ipsets.go (hunk 2 above)
Comment (fasaxc) [reply ipsets/ipsets.go]: No difference, concern is removing from a set that we're iterating over.  As it happens, it is safe to remove from a go map while iterating over it but that's assuming a particular implementation of set.
